name: Run Python Script

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [0, 1, 2, 3, 4]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run python script
        run: |
          python resolve_domain.py --shard-index ${{ matrix.shard }} --total-shards 5
          mv resolve_result.txt resolve_result_${{ matrix.shard }}.txt

      - name: Upload partial artifact
        uses: actions/upload-artifact@v4
        with:
          name: partial-results-${{ matrix.shard }}
          path: resolve_result_${{ matrix.shard }}.txt
          retention-days: 1

  merge-results:
    needs: run-script
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: partial-results-*
          merge-multiple: true

      - name: Merge and Sort results
        run: |
          # Use sort to combine all partial files into one alphabetically sorted final result
          sort artifacts/resolve_result_*.txt > resolve_result.txt

      - name: Upload final artifact
        uses: actions/upload-artifact@v4
        with:
          name: final-resolve-result
          path: resolve_result.txt
